### ISSUE TITLE
Not working on Synology DS918+

### ISSUE THREAD

**Issue by Maudissure** [scooterpsu/Comixology_Ubooquity_2#1]
Hi,

I'm trying this theme on a Synology ds918+ but it seems not working, i get only a spinning wheel on screen and nothing more. Other themes works.

**Comment by scooterpsu** [comment]
This should be sorted with the latest release.  Let me know if it's not.

**Comment by Maudissure** [comment]
OK i can now access and browse collections but neither read nor download direct buttons are working, i need to click on comics or book image for accessing a functionnal reading or download button.

**Comment by scooterpsu** [comment]
Could you open the debug console in your browser (right-click page, inspect, click console for Chrome) and copy-paste the error that's happening when you click read?

**Comment by Maudissure** [comment]
Hum, ok, it works on chrome browser but not on Firefox browser. Dunno why, inspector doesn't show anything when i click on popup button.

**Comment by scooterpsu** [comment]
So while I'm not 100% certain why it just wasn't doing anything on Firefox, I was able to replicate it. Rather than fix my hacky handling of the read/download buttons, I replaced the function. This should solve the issue.

**Comment by Maudissure** [comment]
Ok , popup buttons are functionnals but ... 

If i try to open a PDF in the BOOKS i obtain this : 

```
HTTP ERROR 500

Problem accessing /epubreader/1110011/. Reason:

    Internal server error: null

Powered by Jetty:// 9.4.0.v20161208
```

But, the comics works.

**Comment by scooterpsu** [comment]
Looks like there are multiple reader programs, depending on format. 

Try with the newest themeScript, it should use bookreader for pdfs and epubreader for epubs. Since all other book formats aren't supported, I have it set to either remove the read button or disable it (depending on what looked better in context).

**Comment by Maudissure** [comment]
Seems working but (yes again :D ) : 

When selection on popup buttons : 
![image](https://user-images.githubusercontent.com/41825213/54031649-9b2cd680-41af-11e9-8671-9383880467ca.png)

I get : 
![image](https://user-images.githubusercontent.com/41825213/54031600-80f2f880-41af-11e9-8616-bb606d760f64.png)

See the "Page 1 of NaN" ? Then impossible to change page or browse the book or comics.
All clear when opening book/comics after a click on the picture.

**Comment by scooterpsu** [comment]
Grab the newest release, this should be sorted already. 

Since I can't access the page count without polling metadata for every comic, I left it out of the URL I generated at first (and that happened). 

The new version "fixes" this by hardcoding the page count to 1000 for now. I'm trying to figure a better way to do it, but I'm not sure if it'll be possible without database access.

**Comment by scooterpsu** [comment]
Oh crap, ignore me. My fix is only setup for comics. I'll do the same for books in the interim.

**Comment by Maudissure** [comment]
ok i'll wait ;)

**Comment by scooterpsu** [comment]
Ok, _now_ try the newest release. :)

**Comment by Maudissure** [comment]
Working now but ... i get 1000 pages for all my books/comics :D

**Comment by scooterpsu** [comment]
Yeah, this'll end up being the case until I can figure a better way. But it's at least functional. :)

**Comment by Maudissure** [comment]
yes it's functionnal. Thanks.
